export const ADD_TODO_START = "ADD_TODO_START";
export const ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS";
export const ADD_TODO_FAILED = "ADD_TODO_FAILED";

export const LOAD_TODOS_START = 'LOAD_TODOS_START';
export const LOAD_TODOS_SUCCESS = 'LOAD_TODOS_SUCCESS';
export const LOAD_TODOS_FAILED = 'LOAD_TODOS_FAILED';

export const TOGGLE_CHECKED_STATUS = 'TOGGLE_CHECKED_STATUS';

export const REMOVE_TODOS_START = 'REMOVE_TODOS_START';
export const REMOVE_TODOS_SUCCESS = 'REMOVE_TODOS_SUCCESS';

export const UPDATE_TODO_START = 'UPDATE_TODO_START';
export const UPDATE_TODO_SUCCESS = 'UPDATE_TODO_SUCCESS';

export const REMOVE_TODO_START = 'REMOVE_TODO_START';
export const REMOVE_TODO_SUCCESS = 'REMOVE_TODO_SUCCESS';
